SELECT * FROM Employees_Main1


CREATE VIEW VW AS SELECT * FROM Employees_Main1 WHERE DepartmentID = 10

SELECT * FROM VW


CREATE TABLE ERROR_LOGS(ID INT IDENTITY PRIMARY KEY, ERROR_CODE INT, ERROR_MSG VARCHAR(MAX), 
	ERROR_LINE INT,SEVERITY INT, PROC_NAME VARCHAR(MAX), LOGGED_AT DATETIME DEFAULT GETDATE())



BEGIN TRY
	BEGIN TRANSACTION
		UPDATE Employees_Main1 
		SET Salary = Salary + Salary*0.1
		WHERE DepartmentID = 10
		IF EXISTS(SELECT Salary FROM Employees_Main1 WHERE DepartmentID=10 AND Salary > 100000)
			BEGIN
				RAISERROR('SALARY EXEEDED THE LIMIT',16,1)
			END
		ELSE
			BEGIN
				COMMIT TRANSACTION
				PRINT 'SALARY ADJUSTED'
			END
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION

	PRINT 'ADJUSTMENT FAILED'
	PRINT GETDATE()
	INSERT INTO ERROR_LOGS
	(ERROR_CODE, ERROR_MSG, ERROR_LINE, SEVERITY, PROC_NAME)
	VALUES
	(ERROR_NUMBER(),ERROR_MESSAGE(),ERROR_LINE(), ERROR_SEVERITY(), ERROR_PROCEDURE())
END CATCH


SELECT * FROM ERROR_LOGS

SELECT * FROM Employees_Main1